- name: copying tar.xz file to new location
  file: path={{[ nodeapp_copy_src, nodeapp_copy_dest ]}} state=directory
   

- name: Extracting node_app.tar.xz to /home/manoj/Documents/node_app/node_app
  file: path={{[ nodeapp_unarchive_src, nodeapp_unarchive_dest]}} state=directory 

    
- name: performing npm install
  npm:
    state: present
    path: /home/manoj/Documents/node_app


- name: performing npm start
  shell: nohup npm start --prefix /home/manoj/Documents/node_app &









