

- name: copying tar.xz file to new location
  copy:
    src: /home/manoj/Documents/ansible/roles/defaults/main.yml/{{ nodeapp_copy_src }}
    dest: /home/manoj/Documents/ansible/roles/defaults/main.yml/{{ nodeapp_copy_dest }}


- name: Extracting node_app.tar.xz to /home/manoj/Documents/node_app/node_app 
  unarchive:
    src: /home/manoj/Documents/ansible/roles/defaults/main.yml/{{ nodeapp_unarchive_src }}
    dest: /home/manoj/Documents/ansible/roles/defaults/main.yml/{{ nodeapp_unarchive_dest }}

    
- name: performing npm install
  npm:
    state: present
    path: /home/manoj/Documents/node_app


- name: performing npm start
  shell: nohup npm start --prefix /home/manoj/Documents/node_app &








