
- name: copying tar.xz file to new location
  copy:
    src: '{{ nodeapp_var }}/test2/node_app.tar.xz'
    dest: '{{ nodeapp_var }}/node_app'
  

- name: Extracting node_app.tar.xz to /home/manoj/Documents/node_app/node_app
  unarchive:
    src: '{{ nodeapp_var }}/node_app/node_app.tar.xz'
    dest: '{{ nodeapp_var }}/node_app' 

    
- name: performing npm install
  npm:
    state: present
    path: '{{ nodeapp_var }}/node_app'   


- name: performing pm2 start
  shell: 'pm2 start --name"node_app"{{ nodeapp_var }}/node_app &'

- name: delete existing pm2 process if running
  shell: pm2 delete --name"node_app" & 
